name: Run k6 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install server dependencies
      run: |
        cd server
        yarn install

    - name: Start the server
      run: |
        cd server
        yarn start &

    - name: Wait for server to be ready
      run: sleep 10

    - name: Run k6 tests
      run: |
        docker run --rm -v $PWD:/mnt/loadimpact loadimpact/k6 run /mnt/loadimpact/test.js
